name: 'Set environment variables'
description: 'Configures environment variables from files in repo'
inputs:
  var-file-path:
    description: 'File path or glob to variable file. Default: ./.github/variables/*'
    required: false
    default: ./.github/variables/*
runs:
  using: "composite"
  steps:
    - name: Set env
      shell: bash
      run: |
        sed "" ${{ inputs.var-file-path }} >> $GITHUB_ENV
