name: 'Setup Neon'
description: 'Setup the Neon toolchain.'
inputs:
  target:
    description: 'Target architecture for Rust toolchain.'
    required: false
    default: ''
  use-cross:
    description: 'Install cross-rs?'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      uses: falti/dotenv-action@v1
      with:
        path: ./.github/workflows/.env
        export-variables: true
        keys-case: bypass
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: ${{ env.NPM_REGISTRY }}
        cache: npm
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.RUST_VERSION }}
        target: ${{ inputs['target'] }}
        override: true
    - name: Install cross-rs
      if: ${{ inputs['use-cross'] == 'true' }}
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cross
