name: CI

env:
  NODE_VERSION: 18.x
  PROXY: http://127.0.0.1:4873/
  CIUSER: ci
  CIEMAIL: ci@neon-bindings.com
  CIPASS: dummycipassword

on:
  push:
    # Prevent duplicate runs of this workflow on our own internal PRs.
    branches:
      - main
      - next/*
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
      - next/*

jobs:
  bundles:
    name: Check Bundles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Bundles
        shell: bash
        run: |
          echo "Checking that all bundled tools are up to date..."
          dirty_workspaces=()
          for input_workspace in `find src -type d -mindepth 1 -maxdepth 1 -not -name node_modules` ; do
            output_workspace=$(echo $input_workspace | sed -e 's/^src/pkgs/')
            input_mtime=$(git log -1 --format=%ct $input_workspace)
            output_mtime=$(git log -1 --format=%ct $output_workspace)
            if [[ $input_mtime -gt $output_mtime ]] ; then
              echo "❌ $input_workspace has changed since $output_workspace was last generated"
              dirty_workspaces+=($input_workspace)
            fi
          done
          if [[ ${#dirty_workspaces[@]} -gt 0 ]] ; then
            echo
            echo '💡 Re-run `npm run bundle` on the following workspaces before committing:'
            for workspace in ${dirty_workspaces[*]} ; do
              echo "  • $workspace"
            done
            exit 1
          fi

  integration:
    name: Integration Tests
    needs: [bundles]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Dependencies
        shell: bash
        run: npm ci --verbose
      - name: Build
        uses: neon-actions/build@v0.3.4
        with:
          working-directory: ./pkgs/cargo-messages
          target: linux-x64-gnu
          node-version: ${{ env.NODE_VERSION }}
          use-cross: false
          npm-publish: false
          github-release: false
      - name: Install global tools
        shell: bash
        run: |
          npm install -g verdaccio
          npm install -g npm-cli-adduser
      - name: Start npm Proxy
        shell: bash
        working-directory: ./test/integration/proxy
        run: |
          nohup verdaccio --config ./config.yml --listen ${{ env.PROXY }} &
          # Verdaccio needs up to 10 seconds to boot up and begin accepting connections.
          #sleep 10
          #if [ -e proxy.log ]; then
          #  cat proxy.log
          #fi
          # Wait for the log to exist
          until [ -f proxy.log ]; do
            sleep 2
          done
          # Wait for the server to begin listening for connections
          ( tail -f -n10 proxy.log & ) | fgrep -q 'http://127.0.0.1:4873/'
          cat proxy.log
      - name: Publish @cargo-messages/linux-x64-gnu to proxy
        shell: bash
        run: |
          npm-cli-adduser -u ${{env.CIUSER}} -p ${{env.CIPASS}} -e ${{env.CIEMAIL}} -r ${{env.PROXY}}
          npm publish ./pkgs/cargo-messages/dist/"cargo-messages-linux-x64-gnu-$(jq -r '.version' < ./pkgs/cargo-messages/package.json).tgz" --registry ${{env.PROXY}}
      - name: Publish cargo-messages to proxy
        shell: bash
        working-directory: ./pkgs/cargo-messages
        run: |
          npm-cli-adduser -u ${{env.CIUSER}} -p ${{env.CIPASS}} -e ${{env.CIEMAIL}} -r ${{env.PROXY}}
          npm publish --registry ${{env.PROXY}}
      - name: Publish @neon-rs/load to proxy
        shell: bash
        working-directory: ./pkgs/load
        run: |
          npm-cli-adduser -u ${{env.CIUSER}} -p ${{env.CIPASS}} -e ${{env.CIEMAIL}} -r ${{env.PROXY}}
          npm publish --registry ${{env.PROXY}}
      - name: Publish @neon-rs/cli to proxy
        shell: bash
        working-directory: ./pkgs/cli
        run: |
          npm-cli-adduser -u ${{env.CIUSER}} -p ${{env.CIPASS}} -e ${{env.CIEMAIL}} -r ${{env.PROXY}}
          npm publish --registry ${{env.PROXY}}
