name: Comments

run-name: |
  ${{ (github.event.issue.pull_request
       && contains(github.event.comment.body, '/build-all')
       && format('Dry run (PR #{0})', github.event.issue.number))
   || 'Issue comment (no action)' }}

on:
  issue_comment:
    types: [created]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build-all') }}
    outputs:
      branch: ${{ steps.pr-ref.outputs.branch || github.event.repository.default_branch }}
    steps:
      - name: PR Branch
        if: ${{ github.event.issue.pull_request }}
        id: pr-ref
        shell: bash
        run: echo "branch=$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')" >> "$GITHUB_OUTPUT"
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Diagnostics
        shell: bash
        run: |
          echo "***** github.event:"
          echo '${{ toJSON(github.event) }}'
          echo "***** github.repository:"
          echo '${{ toJSON(github.repository) }}'
          echo "***** github.head_ref:"
          echo 'ref: ${{ github.event_name == 'issue_comment' && github.head_ref }}'
          echo "***** github.event.repository.default_branch:"
          echo '${{ github.event.repository.default_branch }}'
          git branch -a

  dryrun:
    needs: [setup]
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ needs.setup.outputs.branch }}
      update-version: true
      github-release: false
