name: publish

env:
  NODE_VERSION: 18.x
  NPM_REGISTRY: 'https://registry.npmjs.org'

on:
  push:
    tags:
      - v*
      - DRYRUN*

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      action: ${{ steps.action.outputs.type }}
    steps:
      - name: Get Tag Name
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName
      - id: action
        name: Determine Action Type
        shell: bash
        run: |
          if [[ ${{ contains(steps.tagName.outputs.tag, 'DRYRUN') }} == true ]]
          then
            echo type=dryrun
            echo "type=dryrun" >> "$GITHUB_OUTPUT"
          else
            echo type=publish
            echo "type=publish" >> "$GITHUB_OUTPUT"
          fi

  # pack:
  #   name: Pack (cargo-messages)
  #   needs: [setup]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Install Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         registry-url: ${{ env.NPM_REGISTRY }}
  #         cache: npm
  #     - name: Setup Monorepo
  #       shell: bash
  #       run: |
  #         git checkout main
  #         git config --global user.email 'ci@neon-bindings.com'
  #         git config --global user.name 'Neon CI'
  #         npm i
  #         if [[ $(git diff --stat) != '' ]]; then
  #           git commit -a -m 'updated lockfile after setup'
  #         fi
  #     - name: Show Neon CLI Version
  #       shell: bash
  #       run: |
  #         npm explain @neon-rs/cli
  #       working-directory: ./pkgs/cargo-messages
  #     - name: Pack
  #       shell: bash
  #       run: |
  #         mkdir -p dist
  #         npm pack --pack-destination=dist
  #         cat install-builds.log
  #       working-directory: ./pkgs/cargo-messages
  #     - name: Release
  #       if: ${{ needs.setup.outputs.action == 'publish' }}
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: ./pkgs/cargo-messages/dist/*.tgz
  #     # - name: Pack
  #     #   uses: neon-actions/pack@v0.2
  #     #   with:
  #     #     working-directory: ./pkgs/cargo-messages
  #     #     node-version: ${{ env.NODE_VERSION }}
  #     #     github-release: ${{ needs.setup.outputs.action == 'publish' }}

  macos-builds:
    name: Builds (macOS)
    needs: [setup]
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
        #target: [darwin-arm64, darwin-x64]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Monorepo
        shell: bash
        run: |
          git checkout main
          git config --global user.email 'ci@neon-bindings.com'
          git config --global user.name 'Neon CI'
          npm i
          if [[ $(git diff --stat) != '' ]]; then
            git commit -a -m 'updated lockfile after setup'
          fi
      - name: Bump Version (dry-run only)
        if: ${{ needs.setup.outputs.action == 'dryrun' }}
        shell: bash
        run: |
          git branch -a
          npm version patch -m 'dryrun'
          git branch -a
          git status
      - name: Build
        uses: neon-actions/build@v0.2
        with:
          working-directory: ./pkgs/cargo-messages
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: ${{ needs.setup.outputs.action == 'publish' }}

  windows-builds:
    name: Builds (Windows)
    needs: [setup]
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc]
        #target: [win32-x64-msvc, win32-arm64-msvc]
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Monorepo
        shell: bash
        run: |
          git checkout main
          git config --global user.email 'ci@neon-bindings.com'
          git config --global user.name 'Neon CI'
          npm i
          if [[ $(git diff --stat) != '' ]]; then
            git commit -a -m 'updated lockfile after setup'
          fi
      - name: Bump Version (dry-run only)
        if: ${{ needs.setup.outputs.action == 'dryrun' }}
        shell: bash
        run: |
          git branch -a
          npm version patch -m 'dryrun'
          git branch -a
          git status
      - name: Build
        uses: neon-actions/build@v0.2
        with:
          working-directory: ./pkgs/cargo-messages
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: ${{ needs.setup.outputs.action == 'publish' }}

  other-builds:
    name: Builds (other platforms)
    needs: [setup]
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, armv7-linux-androideabi]
        #target: [linux-arm-gnueabihf, linux-x64-gnu, android-arm-eabi]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Monorepo
        shell: bash
        run: |
          git checkout main
          git config --global user.email 'ci@neon-bindings.com'
          git config --global user.name 'Neon CI'
          npm i
          if [[ $(git diff --stat) != '' ]]; then
            git commit -a -m 'updated lockfile after setup'
          fi
      - name: Bump Version (dry-run only)
        if: ${{ needs.setup.outputs.action == 'dryrun' }}
        shell: bash
        run: |
          git branch -a
          npm version patch -m 'dryrun'
          git branch -a
          git status
      - name: Build
        uses: neon-actions/build@v0.2
        with:
          working-directory: ./pkgs/cargo-messages
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          use-cross: true
          npm-publish: false
          github-release: ${{ needs.setup.outputs.action == 'publish' }}

  publish:
    name: Publish
    needs: [setup, macos-builds, windows-builds, other-builds]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Monorepo
        shell: bash
        run: |
          git checkout main
          git config --global user.email 'ci@neon-bindings.com'
          git config --global user.name 'Neon CI'
          npm i
          if [[ $(git diff --stat) != '' ]]; then
            git commit -a -m 'updated lockfile after setup'
          fi
      - name: Publish (cargo-messages)
        if: ${{ needs.setup.outputs.action == 'publish' }}
        uses: neon-actions/publish@v0.4.1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          working-directory: ./pkgs/cargo-messages
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY }}
          fetch-binaries: "*.tgz"
          github-release: true
      - name: Build (@neon-rs/load)
        shell: bash
        run: npm run build
        working-directory: ./pkgs/load
      - name: Publish (@neon-rs/load)
        if: ${{ needs.setup.outputs.action == 'publish' }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
        working-directory: ./pkgs/load
      - name: Update (@neon-rs/cli)
        if: ${{ needs.setup.outputs.action == 'publish' }}
        shell: bash
        run: |
          npm run update-src
          git commit -a -m 'update cli to cargo-messages@latest'
          git push
      - name: Publish (@neon-rs/cli)
        if: ${{ needs.setup.outputs.action == 'publish' }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
        working-directory: ./pkgs/cli
