name: publish

env:
  NODE_VERSION: 18.x
  NPM_REGISTRY: 'https://registry.npmjs.org'

on:
  push:
    tags:
      - v*

jobs:
  pack:
    name: Pack (cargo-messages)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Pack
        uses: neon-actions/pack@v0.1
        with:
          working-directory: ./pkgs/cargo-messages
          node-version: ${{ env.NODE_VERSION }}
          github-release: true

  macos-builds:
    name: Builds (macOS)
    strategy:
      matrix:
        target: [darwin-arm64, darwin-x64]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Build
        uses: neon-actions/build@v0.1.1
        with:
          working-directory: ./pkgs/cargo-messages
          input-directory: npm/${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: true

  windows-builds:
    name: Builds (Windows)
    strategy:
      matrix:
        target: [win32-x64-msvc, win32-arm64-msvc]
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Build
        uses: neon-actions/build@v0.1.1
        with:
          working-directory: ./pkgs/cargo-messages
          input-directory: npm/${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: true

  other-builds:
    name: Builds (other platforms)
    strategy:
      matrix:
        target: [linux-arm-gnueabihf, linux-x64-gnu, android-arm-eabi]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build
        uses: neon-actions/build@v0.1.1
        with:
          working-directory: ./pkgs/cargo-messages
          input-directory: npm/${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          use-cross: true
          npm-publish: false
          github-release: true

  publish:
    name: Publish
    needs: [pack, macos-builds, windows-builds, other-builds]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish (cargo-messages)
        uses: neon-actions/publish@v0.2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          working-directory: ./pkgs/cargo-messages
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY }}
          github-release: "*.tgz"
      - name: Publish (@neon-rs/load)
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npm run build
          npm publish --access public
        working-directory: ./pkgs/load
      - name: Publish (@neon-rs/cli)
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npm run bundle
          cd ../cli
          npm publish --access public
        working-directory: ./pkgs/cli-dev
