name: publish

env:
  NODE_VERSION: 18.x
  NPM_REGISTRY: 'https://registry.npmjs.org'

on:
  push:
    tags:
      - v*
      - DRYRUN*

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      action: ${{ steps.action.outputs.type }}
    steps:
      - name: Get Tag Name
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName
      - id: action
        name: Determine Action Type
        shell: bash
        run: |
          echo ${{ contains(steps.tagName.outputs.tag, 'DRYRUN') }}
          if [[ ${{ contains(steps.tagName.outputs.tag, 'DRYRUN') }} == true ]]
          then
            echo type=dryrun
            echo "type=dryrun" >> "$GITHUB_OUTPUT"
          else
            echo type=publish
            echo "type=publish" >> "$GITHUB_OUTPUT"
          fi

  pack:
    name: Pack (cargo-messages)
    needs: [setup]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Pack
        uses: neon-actions/pack@v0.1
        with:
          working-directory: ./pkgs/cargo-messages
          node-version: ${{ env.NODE_VERSION }}
          github-release: ${{ needs.setup.outputs.action == 'publish' }}

  macos-builds:
    name: Builds (macOS)
    needs: [setup]
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
        #target: [darwin-arm64, darwin-x64]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Build
        uses: neon-actions/build@v0.1
        with:
          working-directory: ./pkgs/cargo-messages
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: ${{ needs.setup.outputs.action == 'publish' }}

  windows-builds:
    name: Builds (Windows)
    needs: [setup]
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc]
        #target: [win32-x64-msvc, win32-arm64-msvc]
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Build
        uses: neon-actions/build@v0.1
        with:
          working-directory: ./pkgs/cargo-messages
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: ${{ needs.setup.outputs.action == 'publish' }}

  other-builds:
    name: Builds (other platforms)
    needs: [setup]
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, armv7-linux-androideabi]
        #target: [linux-arm-gnueabihf, linux-x64-gnu, android-arm-eabi]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build
        uses: neon-actions/build@v0.1
        with:
          working-directory: ./pkgs/cargo-messages
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          use-cross: true
          npm-publish: false
          github-release: ${{ needs.setup.outputs.action == 'publish' }}

  publish:
    name: Publish
    needs: [setup, pack, macos-builds, windows-builds, other-builds]
    if: ${{ needs.setup.outputs.action == 'publish' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Tag Name
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName
      - name: Publish (cargo-messages)
        if: ${{ !contains(steps.tagName.outputs.tag, 'DRYRUN') }}
        uses: neon-actions/publish@v0.2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          working-directory: ./pkgs/cargo-messages
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY }}
          github-release: "*.tgz"
      - name: Publish (@neon-rs/load)
        if: ${{ !contains(steps.tagName.outputs.tag, 'DRYRUN') }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npm run build
          npm publish --access public
        working-directory: ./pkgs/load
      - name: Publish (@neon-rs/cli)
        if: ${{ !contains(steps.tagName.outputs.tag, 'DRYRUN') }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npm run bundle
          cd ../cli
          npm publish --access public
        working-directory: ./pkgs/cli-dev
